# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Anon/Dropbox/projects/UAH/S2019/CPE526/project/CustomController/CustomController.cache/wt [current_project]
set_property parent.project_path C:/Users/Anon/Dropbox/projects/UAH/S2019/CPE526/project/CustomController/CustomController.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Anon/Dropbox/projects/UAH/S2019/CPE526/project/CustomController/CustomController.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv C:/Users/Anon/Dropbox/projects/UAH/S2019/CPE526/project/CustomController/CustomController.srcs/sources_1/new/Root.sv
read_ip -quiet C:/Users/Anon/Dropbox/projects/UAH/S2019/CPE526/project/CustomController/CustomController.srcs/sources_1/ip/ddr4_phy_0/ddr4_phy_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Anon/Dropbox/projects/UAH/S2019/CPE526/project/CustomController/CustomController.srcs/sources_1/ip/ddr4_phy_0/ddr4_phy_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anon/Dropbox/projects/UAH/S2019/CPE526/project/CustomController/CustomController.srcs/sources_1/ip/ddr4_phy_0/par/ddr4_phy_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anon/Dropbox/projects/UAH/S2019/CPE526/project/CustomController/CustomController.srcs/sources_1/ip/ddr4_phy_0/ip_0/ddr4_phy_0_microblaze_mcs_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anon/Dropbox/projects/UAH/S2019/CPE526/project/CustomController/CustomController.srcs/sources_1/ip/ddr4_phy_0/ip_0/ddr4_phy_0_microblaze_mcs_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anon/Dropbox/projects/UAH/S2019/CPE526/project/CustomController/CustomController.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_0/bd_c5bc_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anon/Dropbox/projects/UAH/S2019/CPE526/project/CustomController/CustomController.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_0/bd_c5bc_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anon/Dropbox/projects/UAH/S2019/CPE526/project/CustomController/CustomController.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_1/bd_c5bc_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anon/Dropbox/projects/UAH/S2019/CPE526/project/CustomController/CustomController.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_1/bd_c5bc_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anon/Dropbox/projects/UAH/S2019/CPE526/project/CustomController/CustomController.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_2/bd_c5bc_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anon/Dropbox/projects/UAH/S2019/CPE526/project/CustomController/CustomController.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_3/bd_c5bc_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anon/Dropbox/projects/UAH/S2019/CPE526/project/CustomController/CustomController.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_6/bd_c5bc_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anon/Dropbox/projects/UAH/S2019/CPE526/project/CustomController/CustomController.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_9/bd_c5bc_second_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anon/Dropbox/projects/UAH/S2019/CPE526/project/CustomController/CustomController.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_10/bd_c5bc_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anon/Dropbox/projects/UAH/S2019/CPE526/project/CustomController/CustomController.srcs/sources_1/ip/ddr4_phy_0/bd_0/bd_c5bc_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Anon/Dropbox/projects/UAH/S2019/CPE526/project/CustomController/CustomController.srcs/sources_1/ip/ddr4_phy_0/ip_1/par/ddr4_phy_0_phy_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Root -part xczu7ev-ffvc1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Root.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Root_utilization_synth.rpt -pb Root_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
