# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/ddr4_phy_0.xci
# IP: The module: 'ddr4_phy_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/ip_0/ddr4_phy_0_microblaze_mcs.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr4_phy_0_microblaze_mcs || ORIG_REF_NAME==ddr4_phy_0_microblaze_mcs} -quiet] -quiet

# Block Designs: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/bd_c5bc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc || ORIG_REF_NAME==bd_c5bc} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_0/bd_c5bc_microblaze_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_microblaze_I_0 || ORIG_REF_NAME==bd_c5bc_microblaze_I_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_1/bd_c5bc_rst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_rst_0_0 || ORIG_REF_NAME==bd_c5bc_rst_0_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_2/bd_c5bc_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_ilmb_0 || ORIG_REF_NAME==bd_c5bc_ilmb_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_3/bd_c5bc_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_dlmb_0 || ORIG_REF_NAME==bd_c5bc_dlmb_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_4/bd_c5bc_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_dlmb_cntlr_0 || ORIG_REF_NAME==bd_c5bc_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_5/bd_c5bc_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_ilmb_cntlr_0 || ORIG_REF_NAME==bd_c5bc_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_6/bd_c5bc_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_lmb_bram_I_0 || ORIG_REF_NAME==bd_c5bc_lmb_bram_I_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_7/bd_c5bc_second_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_c5bc_second_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_8/bd_c5bc_second_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_c5bc_second_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_9/bd_c5bc_second_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_c5bc_second_lmb_bram_I_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_10/bd_c5bc_iomodule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_iomodule_0_0 || ORIG_REF_NAME==bd_c5bc_iomodule_0_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/ip_1/ddr4_phy_0_phy.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr4_phy_0_phy || ORIG_REF_NAME==ddr4_phy_0_phy} -quiet] -quiet

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_0/bd_c5bc_microblaze_I_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c5bc_microblaze_I_0 || ORIG_REF_NAME==bd_c5bc_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_0/bd_c5bc_microblaze_I_0_ooc_debug.xdc

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_1/bd_c5bc_rst_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c5bc_rst_0_0 || ORIG_REF_NAME==bd_c5bc_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_1/bd_c5bc_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c5bc_rst_0_0 || ORIG_REF_NAME==bd_c5bc_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_2/bd_c5bc_ilmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c5bc_ilmb_0 || ORIG_REF_NAME==bd_c5bc_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_3/bd_c5bc_dlmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c5bc_dlmb_0 || ORIG_REF_NAME==bd_c5bc_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_6/bd_c5bc_lmb_bram_I_0_ooc.xdc

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_9/bd_c5bc_second_lmb_bram_I_0_ooc.xdc

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_10/bd_c5bc_iomodule_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c5bc_iomodule_0_0 || ORIG_REF_NAME==bd_c5bc_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/bd_c5bc_ooc.xdc

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/ip_0/ddr4_phy_0_microblaze_mcs_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr4_phy_0_microblaze_mcs || ORIG_REF_NAME==ddr4_phy_0_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/ip_0/ddr4_phy_0_microblaze_mcs_ooc.xdc

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/ip_1/par/ddr4_phy_0_phy_ooc.xdc

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/ddr4_phy_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr4_phy_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/par/ddr4_phy_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr4_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/ddr4_phy_0.xci
# IP: The module: 'ddr4_phy_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/ip_0/ddr4_phy_0_microblaze_mcs.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr4_phy_0_microblaze_mcs || ORIG_REF_NAME==ddr4_phy_0_microblaze_mcs} -quiet] -quiet

# Block Designs: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/bd_c5bc.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc || ORIG_REF_NAME==bd_c5bc} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_0/bd_c5bc_microblaze_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_microblaze_I_0 || ORIG_REF_NAME==bd_c5bc_microblaze_I_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_1/bd_c5bc_rst_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_rst_0_0 || ORIG_REF_NAME==bd_c5bc_rst_0_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_2/bd_c5bc_ilmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_ilmb_0 || ORIG_REF_NAME==bd_c5bc_ilmb_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_3/bd_c5bc_dlmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_dlmb_0 || ORIG_REF_NAME==bd_c5bc_dlmb_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_4/bd_c5bc_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_dlmb_cntlr_0 || ORIG_REF_NAME==bd_c5bc_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_5/bd_c5bc_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_ilmb_cntlr_0 || ORIG_REF_NAME==bd_c5bc_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_6/bd_c5bc_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_lmb_bram_I_0 || ORIG_REF_NAME==bd_c5bc_lmb_bram_I_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_7/bd_c5bc_second_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_c5bc_second_dlmb_cntlr_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_8/bd_c5bc_second_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_c5bc_second_ilmb_cntlr_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_9/bd_c5bc_second_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_c5bc_second_lmb_bram_I_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_10/bd_c5bc_iomodule_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c5bc_iomodule_0_0 || ORIG_REF_NAME==bd_c5bc_iomodule_0_0} -quiet] -quiet

# IP: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/ip_1/ddr4_phy_0_phy.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr4_phy_0_phy || ORIG_REF_NAME==ddr4_phy_0_phy} -quiet] -quiet

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_0/bd_c5bc_microblaze_I_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c5bc_microblaze_I_0 || ORIG_REF_NAME==bd_c5bc_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_0/bd_c5bc_microblaze_I_0_ooc_debug.xdc

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_1/bd_c5bc_rst_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c5bc_rst_0_0 || ORIG_REF_NAME==bd_c5bc_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_1/bd_c5bc_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c5bc_rst_0_0 || ORIG_REF_NAME==bd_c5bc_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_2/bd_c5bc_ilmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c5bc_ilmb_0 || ORIG_REF_NAME==bd_c5bc_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_3/bd_c5bc_dlmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c5bc_dlmb_0 || ORIG_REF_NAME==bd_c5bc_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_6/bd_c5bc_lmb_bram_I_0_ooc.xdc

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_9/bd_c5bc_second_lmb_bram_I_0_ooc.xdc

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/ip/ip_10/bd_c5bc_iomodule_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c5bc_iomodule_0_0 || ORIG_REF_NAME==bd_c5bc_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/bd_0/bd_c5bc_ooc.xdc

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/ip_0/ddr4_phy_0_microblaze_mcs_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr4_phy_0_microblaze_mcs || ORIG_REF_NAME==ddr4_phy_0_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/ip_0/ddr4_phy_0_microblaze_mcs_ooc.xdc

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/ip_1/par/ddr4_phy_0_phy_ooc.xdc

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/ddr4_phy_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr4_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/serlop/mem_ctrl/mem_ctrl.srcs/sources_1/ip/ddr4_phy_0/par/ddr4_phy_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr4_phy_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
